### ISSUE TITLE
Xcode 13.3 Beta 3 swift_binary not building

### ISSUE THREAD

**Issue by regularberry** [bazelbuild/rules_swift#775] opened 2022-03-08 16:08 UTC
I've come across an issue with `swift_binary` and `macos_command_line_application` not building with Xcode 13.3 Beta 3 command line tools (specifically the Mac OS 12.3 SDK that ships with it).

At first I thought it was an issue with creating a custom rule and passing in a command line tool as the executable, but from creating a simple test project I've come across something else, which may or may not be related.

I've attached a very simple example project which replicates the issue.

You can build a `swift_binary` using Xcode 13.2.1 with no additional flags, but to build it in Xcode 13.3.0 you'll need `--swiftcopt=-whole-module-optimization` turned on.

The test project provides 3 configs:
* `bazelisk build SimpleCommandLine --config=success` points at Xcode 13.2.1 and succeeds.
* After a `bazel clean --expunge`, `bazelisk build SimpleCommandLine --config=fail` which points at Xcode 13.3.0 will fail
* Finally, `bazelisk build SimpleCommandLine --config=success-with-13.3` will succeed because it turns whole module optimization on.

Please correct me if I'm just not understanding something, I'm still a Bazel novice. 

Thank you for your time!

[SimpleCommandLine.zip](https://github.com/bazelbuild/rules_swift/files/8207686/SimpleCommandLine.zip)

This is using Bazel 5.0.0 and rules_apple 0.33.0.

The error given is:
```
Compiling Swift module //SimpleCommandLine:SimpleCommandLine failed: (Exit 1): worker failed: error executing command 
  (cd /private/var/tmp/_bazel_Z006LFH/efd460bccebb4d2e1f7d3ce9a81ace5b/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=12.3 \
    XCODE_VERSION_OVERRIDE=13.3.0.13E5104i \
  bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/build_bazel_rules_swift/tools/worker/worker swiftc @bazel-out/darwin-dbg/bin/SimpleCommandLine/SimpleCommandLine_SimpleCommandLine.swiftmodule-0.params)
# Configuration: d03c48ef8c2a47edb079909273e751b2045c82b2c50d44193c24ab65b3afcb53
# Execution platform: @local_config_platform//:host
swift_worker: Could not copy bazel-out/darwin-dbg/bin/_swift_incremental/SimpleCommandLine/SimpleCommandLine_objs/main.swift.partial_swiftmodule to bazel-out/darwin-dbg/bin/SimpleCommandLine/SimpleCommandLine_objs/main.swift.partial_swiftmodule (errno 2)
Target //SimpleCommandLine:SimpleCommandLine failed to build
```

**Comment by keith** [comment] 2022-03-12 18:59
I can reproduce this as well, also with Xcode, it seems like this file isn't produced in some cases now, we need to debug more

**Comment by sgammon** [comment] 2022-03-15 21:44
i can reproduce, this just stopped us in our tracks when we upgraded Xcode to 13.3.0 ☹️

**Comment by keith** [comment] 2022-03-15 21:46
As a temporary workaround you can add `-wmo` to `copts` of `swift_binary` targets

**Comment by sgammon** [comment] 2022-03-15 21:49
thanks for the quick reply and all of your hard work on this library, @keith 😄

unfortunately `--swiftcopt=-whole-module-optimization` doesn't fix for us. the failure is occurring within `SwiftProtobuf`, so i'm not sure how to apply that flag unless it's bazel-wide. our targets originate from `swift_library` and `ios_application`.

you were so quick on your comment that i've yet to complete an Xcode 13.2.1 download, but i'm going to try restoring my toolchain and see if that clears this up.

**Comment by keith** [comment] 2022-03-15 21:53
ah it's probably because it's for the host configuration, so you'd also have to pass `--host_swiftcopt=-whole-module-optimization` or set `--features=swift.opt_uses_osize` which applies to all configurations for opt builds (which the host configuration uses)

**Comment by sgammon** [comment] 2022-03-15 21:59
```
build --host_swiftcopt=-whole-module-optimization
```

```
build --features=swift.opt_uses_osize
```

```
build --host_swiftcopt=-whole-module-optimization
build --features=swift.opt_uses_osize
```

and

```
build --swiftcopt=-whole-module-optimization
```

all fail in my case with the same message:

```
swift_worker: Could not copy bazel-out/ios-sim_arm64-min14.0-applebin_ios-ios_sim_arm64-fastbuild-ST-3d618853b8a4/bin/_swift_incremental/external/com_github_apple_swift_protobuf/SwiftProtobuf_objs/Sources/SwiftProtobuf/AnyMessageStorage.swift.partial_swiftmodule to bazel-out/ios-sim_arm64-min14.0-applebin_ios-ios_sim_arm64-fastbuild-ST-3d618853b8a4/bin/external/com_github_apple_swift_protobuf/SwiftProtobuf_objs/Sources/SwiftProtobuf/AnyMessageStorage.swift.partial_swiftmodule (errno 2)
```

previously these builds had succeeded, so it leads me to believe it's the same issue. i haven't upgraded SwiftProtobuf -- it's a transitive dependency, in this case, from `rules_swift`. i'm on `rules_swift` latest. i'm going to give the `13.2.1` toolchain a try, but i know how integrated xcode et. all is into macOS, so 🤞🏻

**Comment by sgammon** [comment] 2022-03-15 22:07
okay, downloading `13.2.1` from [here](https://developer.apple.com/download/all/?q=xcode), decompressing, and running...

```
bazel clean --expunge
bazel shutdown
sudo mv /Applications/Xcode.app /Applications/Xcode_v13_3.app
sudo mv ~/Downloads/Xcode.app /Applications
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
bazel build //...
```

everything's building again.

**Comment by thii** [comment] 2022-03-15 22:22
Looks like none of your build options combinations contains both --swiftcopt=-wmo and --host_swiftcopt=-wmo?

**Comment by keith** [comment] 2022-03-17 19:26
As a potentially better short term workaround you can pass `--swiftcopt=-no-emit-module-separately`. I'm not sure what downsides this has yet

**Comment by keith** [comment] 2022-03-17 19:50
I _think_ we can just drop this requirement https://github.com/bazelbuild/rules_swift/pull/781

**Comment by keith** [comment] 2022-03-18 00:38
I've merged this, please test with HEAD, once I hear back I can work on a new release. I tested with Xcode 13.2.1 and 13.3 and also I tested incremental builds and they passed correctly AFAICT

**Comment by keith** [comment] 2022-03-21 05:17
I'm reverting this and going with another fix, details on https://github.com/bazelbuild/rules_swift/pull/784

**Comment by keith** [comment] 2022-03-21 21:10
So the core issue turned out to be https://github.com/apple/swift-driver/pull/1036, with that, and https://github.com/bazelbuild/rules_swift/pull/781 things work as expected

**Comment by keith** [comment] 2022-03-22 01:19
Ok after even more investigation, that issue is a red-herring (although also a real issue), it seems that https://github.com/bazelbuild/rules_swift/pull/786 is the actual fix we need

**Closed** 2022-03-22 01:23 UTC

**Comment by keith** [comment] 2022-03-22 01:24
Please test with the new change and I will actually create a release as long as we don't find any new issues in the next day or so

**Comment by regularberry** [comment] 2022-03-22 18:39
I've tested the fix in 7b8558cab8e402eb21e2fc655989bae378171486 and it's working for me, thank you!

**Comment by VegetarianZombie** [comment] 2022-03-23 18:06
I'm still getting the same error. I have my workspace set up to use the commit:

```
git_repository(
    name = "build_bazel_rules_swift",
    remote = "https://github.com/bazelbuild/rules_swift.git",
    commit = "7b8558cab8e402eb21e2fc655989bae378171486",
    #tag = "0.26.0",
)
```

Doing a Bazel clean, then a Bazel build is producing the same compile error. 

`swift_worker: Could not copy bazel-out/ios-x86_64-min14.0-applebin_ios-ios_x86_64-fastbuild-ST-67e90b6cfecd/bin/_swift_incremental/bullseye/sources_objs/Bullseye/Sources/BackgroundView.swift.partial_swiftmodule to bazel-out/ios-x86_64-min14.0-applebin_ios-ios_x86_64-fastbuild-ST-67e90b6cfecd/bin/bullseye/sources_objs/Bullseye/Sources/BackgroundView.swift.partial_swiftmodule (errno 2)`

**Comment by keith** [comment] 2022-03-23 18:09
Are you loading rules_apple above this? if so it's likely not respecting this version since rules apple loads a pinned version first

**Comment by VegetarianZombie** [comment] 2022-03-23 19:00
Hi Keith, that looks to have been the problem. I was able to compile the build. Thanks so much for your help!
