### ISSUE TITLE
Objective-C++ Code Compiled as Objective-C

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/rules_swift#994] opened 2023-01-31 06:43 UTC
I am trying to implement Swift wrappers around a C++ library using Objective-C++ as the bridging code. However, when I try to build the Swift code, it fails with a number of build errors that seem to suggest that the Objective-C++ (and the C++ code it depends on) were built as Objective-C instead.

I have a minimal repro case here: https://github.com/davidzchen/bazel-objcpp-swift-interop

When I originally encountered this issue, there were also errors like `error: unknown type name 'namespace'`, but I have not been able to get this error to appear in the minimum repro case.

What might be the cause here? If it is the case that all of the code is being built as Objective-C instead of Objective-C++, is there a way to force the rules to compile as Objective-C++ using some flag?

**Comment by jiawen** [comment] 2023-01-31 15:41
I took a glance at your code. The issue isn't one of Bazel - it's one of Swift. It does not have C++ interop, only C (and Objective-C) interop. C and Objective-C do not understand `namespace`.

**Comment by davidzchen** [comment] 2023-02-01 07:13
Yes, I am aware that Swift does not have C++ interop, but it is well-documented that a workaround is to use Objective-C++ as the bridging code ([for example](https://anuragajwani.medium.com/how-to-consume-c-code-in-swift-b4d64a04e989)).

I can build the `objc_library` targets without any issue since Objective-C++ should support namespaces. However, the problem is that when the Swift code is built, it seems that the Objective-C++ code, along with the underlying C++ code, is built as Objective-C instead.

**Comment by jiawen** [comment] 2023-02-01 14:13
Oh, I took a closer look. You have your Objective-C and Objective-C++ code swapped. Your cc_library seems to contain Objective-C code while your objc_library seems to contain C++ code.

**Comment by davidzchen** [comment] 2023-02-03 08:44
How so? The `cc_library` only includes C++ code (`greeter.cc`, `greeter.h` and a dependency on the Abseil `strings` library), and the `objc_library` only contains the objc++ code. Is the problem that the `objc_library` takes a dependency on the `cc_library`?

```
cc_library(
    name = "greeter",
    srcs = ["greeter.cc"],
    hdrs = ["greeter.h"],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)

objc_library(
    name = "REPGreeter",
    srcs = ["REPGreeter.mm"],
    hdrs = ["REPGreeter.h"],
    deps = [
        ":greeter",
    ],
    copts = ["-std=gnu++14"],
    target_compatible_with = ["@platforms//os:macos"],
)

swift_binary(
    name = "main",
    srcs = ["main.swift"],
    module_name = "main",
    deps = [":REPGreeter"],
)
```

**Comment by jiawen** [comment] 2023-02-15 20:43
Sorry, I misread that. The issue is that in `REPGreeter.h`, you have `#include "greeter.h"`, which uses the preprocessor to inline a bunch of C++ code. That obviously doesn't work. But since `REPGreeter.h` is an Objective-C header declaring an interface, it doesn't need even need to be aware of the C++ type.

In [my PR that fixes it](https://github.com/davidzchen/bazel-objcpp-swift-interop/pull/1), I simply moved the `#include` to the `.mm` file.

This pattern should work for more sophisticated projects as well. LMK if you have more fun issues where you need to define more sophisticated C / Obj-C APIs around complex C++ code.

-jiawen (Xoogler)

**Comment by jiawen** [comment] 2023-07-28 13:32
Shall we close this as resolved?

**Closed** 2023-07-28 17:37 UTC
