### ISSUE TITLE
"Automatically download a Linux toolchain from swift.org if one is not already installed"

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_swift#69] opened 2018-10-02 15:05 UTC
(quoted from README.md)

I'm very interested in this feature.  Does someone have an idea on how close we are on this and/or difficult this is?

**Comment by allevato** [comment] 2019-01-18 15:40
This is a duplicate of #4. No timeline at this time, unfortunately (we welcome PRs if anyone is interested in trying this out).

**Closed by allevato** 2019-01-18 15:40 UTC
